---

- name: Add atomic repository
  template: src=atomic.repo.j2
            dest=/etc/yum.repos.d/atomic.repo
            owner=root
            group=root
            mode=0644

# https://www.atomicorp.com/RPM-GPG-KEY.art.txt
- name: Add atomic GPG key
  copy: src=RPM-GPG-KEY.art.txt  
        dest=/etc/pki/rpm-gpg/RPM-GPG-KEY.art.txt 
        owner=root 
        group=root 
        mode=0644

- name: Install ossec authd init script
  template: src=ossec-authd.j2
            dest=/etc/init.d/ossec-authd
            owner=root 
            group=root
            mode=0755

- name: Install ossec server
  yum: name=ossec-hids-server 
       state=installed
  notify:
    - Initialize ossec

- name: Install ossec server private SSL key
  copy: src=ossec.key
        dest=/var/ossec/etc/sslmanager.key
        owner=root
        group=root
        mode=0600

- name: Install ossec server public SSL cert
  copy: src=ossec.cer
        dest=/var/ossec/etc/sslmanager.cert
        owner=root 
        group=root 
        mode=0644

- name: Set ossec server config
  template: src=ossec-server.conf.j2 
            dest=/var/ossec/etc/ossec-server.conf
  notify:
    - Restart ossec

- name: Copy local rules
  copy: src=local_rules.xml 
        dest=/var/ossec/rules

- name: Set iptables configuration
  template: src=100_ossec_server.j2
            dest=/etc/ferm/ferm.d/100_ossec_server 
            owner=root 
            group=root

- name: Ensure ossec server is running and enabled at start up
  service: name={{ item }}
           state=started
           enabled=yes
  with_items:
    - ossec-hids
    - ossec-authd